[build]
  command = "node generate-manifest.js"
  publish = "."

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Access-Control-Allow-Origin = "*"
