[build]
  command = "node build.js"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=0, must-revalidate"
